server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie
      timeout: 30m

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ggshop?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: GGshop
    password: "1234"
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/comment_schema.sql

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 20MB
      max-request-size: 60MB

app:
  file:
    root-path: C:/Users/chanh/uploads

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.app.ggshop.v1.domain; com.app.ggshop.v1.dto;
  type-handlers-package: com.app.ggshop.v1.mybatis.handler
